### ISSUE TITLE
EDDN Chart Download Error

### ISSUE THREAD

**Issue by j-lutz** [stsichler/ChartButlerCS#1]
Wenn ich versuche EDDN herunterzuladen kommt es zu folgendem Fehler:
![image](https://user-images.githubusercontent.com/10211887/163497210-372c3a6d-30ac-4da9-92bd-0e2bc9a1aa17.png)

Kann man hier evtl. ein Try/Catch herumbauen, ohne dass die komplette Aktualisierung abbricht und man nicht weiß warum. Oder eine sprechende Fehlermeldung ausgeben, bei welchem Flugplatz es ein Problem gab, damit man diesen aus der Liste herausnehmen kann?

Happy Landings
Johannes Lutz

**Comment by stsichler** [comment]
Servus,
ich hab's mir schon angeschaut und glaube, dass es keine gute Idee wäre die Aktualisierung trotz dieses Fehlers für die anderen Flugplätze weiter laufen zu lassen, denn dann wäre die Kartendatenbank danach in einem ungültigen Zustand, d.h. die würde als "aktualisiert auf den derzeitigen AIP Stand" gelten, hätte aber bei EDDN noch ältere bzw. fehlerhafte Karten.
Stattdessen wäre es meiner Meinung nach sinnvoller, genau wie Sie alternativ vorschlagen, durch eine entsprechende Meldung erkennbar zu machen bei welchem Flugplatz der Download fehlerhaft war.
Das gibt dem Benutzer dann die Möglichkeit den Flugplatz manuell aus der Kartensammlung zu entfernen, bevor ein erneuter Aktualisierungsversuch gestartet wird.
Ich schaue mir gerade an, wie ich das hin bekomme.

**Comment by stsichler** [comment]
Die Situation sollte sich mit commit 8397de8b9e2f2c256b93c7cc854f1763f298054b verbessert haben, siehe [Release v1.6.1.1](https://github.com/stsichler/ChartButlerCS/releases/tag/v1.6.1.1).

**Comment by j-lutz** [comment]
Vielen Dank für die schnelle Hilfe, jetzt kann man schnell identifizieren, bei welchem Flugplatz es ein Problem gibt.
Mal sehen wann EDDN gefixxt wird.
